[tool.poetry]
name = "smoothify"
version = "0.1.0"
description = "Buttery smooth Spotify playlists ğŸ‘"
readme = "README.md"
authors = ["Krishna Penukonda <penukonda.krishna.moorthy@gmail.com>"]

[tool.poetry.urls]
homepage = "https://github.com/tasercake/smoothify"
repository = "https://github.com/tasercake/smoothify"

[tool.poetry.dependencies]
# Core
python = ">=3.9,<3.11"
tekore = "^4.3.0"
numpy = "^1.22.3"
scipy = "^1.8.0"
pandas = "^1.4.2"
scikit-learn = "^1.0.2"
joblib = "^1.1.0"
tqdm = "^4.64.0"
julia = "^0.5.7"
click = "^8.1.2"
structlog = "^21.5.0"

[tool.poetry.dev-dependencies]
# Visualization & notebooks
jupyterlab = "^3.3.3"
ipywidgets = "^7.7.0"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"
bokeh = "^2.4.2"
hdbscan = "^0.8.28"
# Dev tools
black = "^22.3.0"
mypy = "^0.942"
pytest = "^7.1.1"
vulture = "^2.3"

[tool.poetry.scripts]
smoothify = "smoothify.__main__:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
